using ColdTrace.Platform.AssetManagement.Domain.Model.Commands;
using ColdTrace.Platform.Shared.Domain.Model.Entities;

namespace ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates;

/// <summary>
///     IoT device aggregate for the asset management context.
/// </summary>
public class IotDevice : IAuditableEntity
{
    /// <summary>
    ///     Protected parameterless constructor for EF Core.
    /// </summary>
    protected IotDevice()
    {
        Uuid = string.Empty;
        Name = string.Empty;
        DeviceType = string.Empty;
        Model = string.Empty;
        MeasurementType = string.Empty;
        Status = string.Empty;
        CalibrationStatus = string.Empty;
    }

    /// <summary>
    ///     Creates an IoT device from a create command.
    /// </summary>
    /// <param name="command">Command containing device data.</param>
    public IotDevice(CreateIotDeviceCommand command)
    {
        OrganizationId = command.OrganizationId;
        GatewayId = command.GatewayId;
        AssetId = command.AssetId;
        Uuid = command.Uuid;
        Name = command.Model;
        DeviceType = command.DeviceType;
        Model = command.Model;
        MeasurementType = command.MeasurementType;
        MeasurementParameterEntries = command.MeasurementParameters
            .Select(measurementParameter => new IotDeviceMeasurementParameter(measurementParameter))
            .ToList();
        ReadingFrequencySeconds = command.ReadingFrequencySeconds;
        Status = command.Status;
        CalibrationStatus = command.CalibrationStatus;
        LastCalibrationDate = command.LastCalibrationDate;
        NextCalibrationDate = command.NextCalibrationDate;
    }

    /// <summary>
    ///     Gets the server-generated device identifier.
    /// </summary>
    public int Id { get; private set; }

    /// <summary>
    ///     Gets the owning organization identifier.
    /// </summary>
    public int OrganizationId { get; private set; }

    /// <summary>
    ///     Gets the connected gateway identifier.
    /// </summary>
    public int GatewayId { get; private set; }

    /// <summary>
    ///     Gets the optional assigned asset identifier.
    /// </summary>
    public int? AssetId { get; private set; }

    /// <summary>
    ///     Gets the connected gateway.
    /// </summary>
    public Gateway Gateway { get; private set; } = null!;

    /// <summary>
    ///     Gets the assigned asset.
    /// </summary>
    public Asset? Asset { get; private set; }

    /// <summary>
    ///     Gets the device unique identifier.
    /// </summary>
    public string Uuid { get; private set; }

    /// <summary>
    ///     Gets the device name.
    /// </summary>
    public string Name { get; private set; }

    /// <summary>
    ///     Gets the supported device type.
    /// </summary>
    public string DeviceType { get; private set; }

    /// <summary>
    ///     Gets the device model.
    /// </summary>
    public string Model { get; private set; }

    /// <summary>
    ///     Gets the human-readable measurement type.
    /// </summary>
    public string MeasurementType { get; private set; }

    /// <summary>
    ///     Gets the telemetry parameters generated by the device.
    /// </summary>
    public List<IotDeviceMeasurementParameter> MeasurementParameterEntries { get; private set; } = [];

    /// <summary>
    ///     Gets the telemetry parameters generated by the device.
    /// </summary>
    public IReadOnlyList<string> MeasurementParameters =>
        MeasurementParameterEntries.Select(entry => entry.MeasurementParameter).ToList();

    /// <summary>
    ///     Gets the expected reading cadence in seconds.
    /// </summary>
    public int ReadingFrequencySeconds { get; private set; }

    /// <summary>
    ///     Gets the device status.
    /// </summary>
    public string Status { get; private set; }

    /// <summary>
    ///     Gets the calibration status.
    /// </summary>
    public string CalibrationStatus { get; private set; }

    /// <summary>
    ///     Gets the last calibration date.
    /// </summary>
    public DateOnly LastCalibrationDate { get; private set; }

    /// <summary>
    ///     Gets the next calibration date.
    /// </summary>
    public DateOnly NextCalibrationDate { get; private set; }

    /// <inheritdoc />
    public DateTimeOffset? CreatedAt { get; set; }

    /// <inheritdoc />
    public DateTimeOffset? UpdatedAt { get; set; }

    /// <summary>
    ///     Updates device data.
    /// </summary>
    /// <param name="command">Command containing updated data.</param>
    public void Update(UpdateIotDeviceCommand command)
    {
        GatewayId = command.GatewayId;
        AssetId = command.AssetId;
        Uuid = command.Uuid;
        Name = command.Model;
        DeviceType = command.DeviceType;
        Model = command.Model;
        MeasurementType = command.MeasurementType;
        MeasurementParameterEntries = command.MeasurementParameters
            .Select(measurementParameter => new IotDeviceMeasurementParameter(measurementParameter))
            .ToList();
        ReadingFrequencySeconds = command.ReadingFrequencySeconds;
        Status = command.Status;
        CalibrationStatus = command.CalibrationStatus;
        LastCalibrationDate = command.LastCalibrationDate;
        NextCalibrationDate = command.NextCalibrationDate;
    }
}
