using System.ComponentModel.DataAnnotations;
using Swashbuckle.AspNetCore.Annotations;

namespace ColdTrace.Platform.AssetManagement.Interfaces.Rest.Resources;

/// <summary>
///     Request resource used to create an IoT device.
/// </summary>
[SwaggerSchema(Description = "Request payload to create an organization-scoped IoT device")]
public record CreateIotDeviceResource(
    [Required]
    [SwaggerParameter(Description = "Connected gateway identifier")]
    int GatewayId,
    [Required]
    [SwaggerParameter(Description = "Device unique identifier")]
    string Uuid,
    [Required]
    [SwaggerParameter(Description = "Supported device type")]
    string DeviceType,
    [Required]
    [SwaggerParameter(Description = "Device model")]
    string Model,
    [Required]
    [SwaggerParameter(Description = "Human-readable measurement type")]
    string MeasurementType,
    [SwaggerParameter(Description = "Telemetry parameters generated by the device")]
    IReadOnlyList<string>? MeasurementParameters,
    [Required]
    [SwaggerParameter(Description = "Expected reading cadence in seconds")]
    int? ReadingFrequencySeconds,
    [SwaggerParameter(Description = "Optional assigned asset identifier")]
    int? AssetId,
    [Required]
    [SwaggerParameter(Description = "Device status")]
    string Status,
    [Required]
    [SwaggerParameter(Description = "Calibration status")]
    string CalibrationStatus,
    [Required]
    [SwaggerParameter(Description = "Last calibration date")]
    DateOnly? LastCalibrationDate,
    [Required]
    [SwaggerParameter(Description = "Next calibration date")]
    DateOnly? NextCalibrationDate);
