using Swashbuckle.AspNetCore.Annotations;

namespace ColdTrace.Platform.AssetManagement.Interfaces.REST.Resources;

/// <summary>
///     Response resource representing an IoT device.
/// </summary>
[SwaggerSchema(Description = "An IoT device resource")]
public record IotDeviceResource(
    [SwaggerParameter(Description = "IoT device identifier")]
    int Id,
    [SwaggerParameter(Description = "Organization identifier")]
    int OrganizationId,
    [SwaggerParameter(Description = "Connected gateway identifier")]
    int GatewayId,
    [SwaggerParameter(Description = "Device unique identifier")]
    string Uuid,
    [SwaggerParameter(Description = "Supported device type")]
    string DeviceType,
    [SwaggerParameter(Description = "Device model")]
    string Model,
    [SwaggerParameter(Description = "Human-readable measurement type")]
    string MeasurementType,
    [SwaggerParameter(Description = "Telemetry parameters generated by the device")]
    IReadOnlyList<string> MeasurementParameters,
    [SwaggerParameter(Description = "Expected reading cadence in seconds")]
    int ReadingFrequencySeconds,
    [SwaggerParameter(Description = "Optional assigned asset identifier")]
    int? AssetId,
    [SwaggerParameter(Description = "Device status")]
    string Status,
    [SwaggerParameter(Description = "Calibration status")]
    string CalibrationStatus,
    [SwaggerParameter(Description = "Last calibration date")]
    DateOnly LastCalibrationDate,
    [SwaggerParameter(Description = "Next calibration date")]
    DateOnly NextCalibrationDate);
