namespace ColdTrace.Platform.AssetManagement.Domain.Model.Commands;

/// <summary>
///     Command for creating an organization-scoped IoT device.
/// </summary>
public record CreateIotDeviceCommand
{
    /// <summary>
    ///     Creates a command with validated and normalized IoT device data.
    /// </summary>
    public CreateIotDeviceCommand(
        int organizationId,
        int gatewayId,
        int? assetId,
        string uuid,
        string deviceType,
        string model,
        string measurementType,
        IEnumerable<string>? measurementParameters,
        int? readingFrequencySeconds,
        string status,
        string calibrationStatus,
        DateOnly? lastCalibrationDate,
        DateOnly? nextCalibrationDate)
    {
        OrganizationId = RequirePositive(organizationId, nameof(organizationId));
        GatewayId = RequirePositive(gatewayId, nameof(gatewayId));
        AssetId = RequirePositiveOrNull(assetId, nameof(assetId));
        Uuid = RequireNonBlank(uuid);
        DeviceType = RequireNonBlank(deviceType);
        Model = RequireNonBlank(model);
        MeasurementType = RequireNonBlank(measurementType);
        MeasurementParameters = NormalizeParameters(measurementParameters, MeasurementType);
        ReadingFrequencySeconds = RequirePositive(readingFrequencySeconds ?? 3600, nameof(readingFrequencySeconds));
        Status = RequireNonBlank(status).ToLowerInvariant();
        CalibrationStatus = RequireNonBlank(calibrationStatus).ToLowerInvariant();
        LastCalibrationDate = lastCalibrationDate ?? throw new ArgumentException("lastCalibrationDate is required.");
        NextCalibrationDate = nextCalibrationDate ?? throw new ArgumentException("nextCalibrationDate is required.");
    }

    /// <summary>
    ///     Gets the owning organization identifier.
    /// </summary>
    public int OrganizationId { get; init; }

    /// <summary>
    ///     Gets the connected gateway identifier.
    /// </summary>
    public int GatewayId { get; init; }

    /// <summary>
    ///     Gets the optional assigned asset identifier.
    /// </summary>
    public int? AssetId { get; init; }

    /// <summary>
    ///     Gets the device unique identifier.
    /// </summary>
    public string Uuid { get; init; }

    /// <summary>
    ///     Gets the supported device type.
    /// </summary>
    public string DeviceType { get; init; }

    /// <summary>
    ///     Gets the device model.
    /// </summary>
    public string Model { get; init; }

    /// <summary>
    ///     Gets the human-readable measurement type.
    /// </summary>
    public string MeasurementType { get; init; }

    /// <summary>
    ///     Gets the telemetry parameters generated by the device.
    /// </summary>
    public IReadOnlyList<string> MeasurementParameters { get; init; }

    /// <summary>
    ///     Gets the expected reading cadence in seconds.
    /// </summary>
    public int ReadingFrequencySeconds { get; init; }

    /// <summary>
    ///     Gets the device status.
    /// </summary>
    public string Status { get; init; }

    /// <summary>
    ///     Gets the calibration status.
    /// </summary>
    public string CalibrationStatus { get; init; }

    /// <summary>
    ///     Gets the last calibration date.
    /// </summary>
    public DateOnly LastCalibrationDate { get; init; }

    /// <summary>
    ///     Gets the next calibration date.
    /// </summary>
    public DateOnly NextCalibrationDate { get; init; }

    private static int RequirePositive(int value, string name)
    {
        if (value <= 0) throw new ArgumentException($"{name} must be positive.");
        return value;
    }

    private static int RequirePositive(int? value, string name)
    {
        if (value is null or <= 0) throw new ArgumentException($"{name} must be positive.");
        return value.Value;
    }

    private static int? RequirePositiveOrNull(int? value, string name)
    {
        if (value is <= 0) throw new ArgumentException($"{name} must be positive when provided.");
        return value;
    }

    private static string RequireNonBlank(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) throw new ArgumentException("Required value cannot be blank.");
        return value.Trim();
    }

    private static IReadOnlyList<string> NormalizeParameters(IEnumerable<string>? values, string measurementType)
    {
        var normalized = values?
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim().ToLowerInvariant())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList() ?? [];
        return normalized.Count > 0
            ? normalized
            : [measurementType.Trim().ToLowerInvariant().Replace(" ", "-")];
    }
}
