// <auto-generated />
using System;
using ColdTrace.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColdTrace.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619100000_AddMaintenanceSchedules")]
    partial class AddMaintenanceSchedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ColdTrace.Platform.MaintenanceManagement.Domain.Model.Aggregates.MaintenanceSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("FrequencyDays")
                        .HasColumnType("int")
                        .HasColumnName("frequency_days");

                    b.Property<string>("Observations")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("observations");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTimeOffset>("ScheduledDate")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_maintenance_schedules");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_maintenance_schedules_asset_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_maintenance_schedules_organization_id");

                    b.ToTable("maintenance_schedules");
                });

            modelBuilder.Entity("ColdTrace.Platform.MaintenanceManagement.Domain.Model.Aggregates.MaintenanceSchedule", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_maintenance_schedules_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_maintenance_schedules_organizations_organization_id");

                    b.Navigation("Asset");

                    b.Navigation("Organization");
                });
#pragma warning restore 612, 618
        }
    }
}
