// <auto-generated />
using System;
using ColdTrace.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColdTrace.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619150142_AddReports")]
    partial class AddReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("acknowledged_by");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("AssetName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("asset_name");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("detected_at");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset?>("LastNotificationAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_notification_at");

                    b.Property<string>("LastNotificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("last_notification_status");

                    b.Property<int>("NotificationCount")
                        .HasColumnType("int")
                        .HasColumnName("notification_count");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("ReadingId")
                        .HasColumnType("int")
                        .HasColumnName("reading_id");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_incidents");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_incidents_asset_id");

                    b.HasIndex("OrganizationId", "AssetId")
                        .HasDatabaseName("i_x_incidents_organization_id_asset_id");

                    b.HasIndex("OrganizationId", "ReadingId")
                        .HasDatabaseName("i_x_incidents_organization_id_reading_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("i_x_incidents_organization_id_status");

                    b.ToTable("incidents");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("delivered_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("message");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Recipient")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("recipient");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("i_x_notifications_incident_id");

                    b.HasIndex("OrganizationId", "IncidentId")
                        .HasDatabaseName("i_x_notifications_organization_id_incident_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("Capacity")
                        .HasColumnType("double")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_assets");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("i_x_assets_location_id");

                    b.HasIndex("OrganizationId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_assets_organization_id_uuid");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Gateway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("network");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_gateways");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("i_x_gateways_location_id");

                    b.HasIndex("OrganizationId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_gateways_organization_id_uuid");

                    b.ToTable("gateways");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_locations");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_locations_organization_id_name");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("commercial_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tax_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organizations");

                    b.HasIndex("ContactEmail")
                        .IsUnique()
                        .HasDatabaseName("i_x_organizations_contact_email");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("i_x_organizations_tax_id");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_roles_name");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Super Administrator",
                            Name = "super-admin"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Administrator",
                            Name = "administrator"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Operations Manager",
                            Name = "operations-manager"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Operator",
                            Name = "operator"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Auditor",
                            Name = "auditor"
                        });
                });

            modelBuilder.Entity("ColdTrace.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("last_name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("OrganizationUserId")
                        .HasColumnType("int")
                        .HasColumnName("organization_user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Uuid")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_users_organization_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_users_role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ColdTrace.Platform.MaintenanceManagement.Domain.Model.Aggregates.MaintenanceSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("FrequencyDays")
                        .HasColumnType("int")
                        .HasColumnName("frequency_days");

                    b.Property<string>("Observations")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("observations");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTimeOffset>("ScheduledDate")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_maintenance_schedules");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_maintenance_schedules_asset_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_maintenance_schedules_organization_id");

                    b.ToTable("maintenance_schedules");
                });

            modelBuilder.Entity("ColdTrace.Platform.MaintenanceManagement.Domain.Model.Aggregates.TechnicalServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<int>("AssetLocationId")
                        .HasColumnType("int")
                        .HasColumnName("asset_location_id");

                    b.Property<string>("AssetName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("asset_name");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("closed_by");

                    b.Property<string>("ClosureSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("closure_summary");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("evidence");

                    b.Property<int?>("IncidentId")
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("issue_description");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_technical_service_requests");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_technical_service_requests_asset_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_technical_service_requests_organization_id");

                    b.ToTable("technical_service_requests");
                });

            modelBuilder.Entity("ColdTrace.Platform.Reports.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssetCount")
                        .HasColumnType("int")
                        .HasColumnName("asset_count");

                    b.Property<double?>("AverageHumidity")
                        .HasColumnType("double")
                        .HasColumnName("average_humidity");

                    b.Property<double?>("AverageTemperature")
                        .HasColumnType("double")
                        .HasColumnName("average_temperature");

                    b.Property<double?>("CompliancePercentage")
                        .HasColumnType("double")
                        .HasColumnName("compliance_percentage");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("generated_at");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("int")
                        .HasColumnName("incident_count");

                    b.Property<int>("OpenIncidentCount")
                        .HasColumnType("int")
                        .HasColumnName("open_incident_count");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("OutOfRangeReadingCount")
                        .HasColumnType("int")
                        .HasColumnName("out_of_range_reading_count");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("datetime")
                        .HasColumnName("period_start");

                    b.Property<int>("ReadingCount")
                        .HasColumnType("int")
                        .HasColumnName("reading_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_reports");

                    b.HasIndex("OrganizationId", "GeneratedAt")
                        .HasDatabaseName("i_x_reports_organization_id_generated_at");

                    b.HasIndex("OrganizationId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_reports_organization_id_uuid");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Incident", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_incidents_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_incidents_organizations_organization_id");

                    b.Navigation("Asset");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Notification", b =>
                {
                    b.HasOne("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications_incidents_incident_id");

                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications_organizations_organization_id");

                    b.Navigation("Incident");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_assets_locations_location_id");

                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assets_organizations_organization_id");

                    b.Navigation("Location");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Gateway", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_gateways_locations_location_id");

                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_gateways_organizations_organization_id");

                    b.Navigation("Location");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", b =>
                {
                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_locations_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Role", b =>
                {
                    b.OwnsMany("ColdTrace.Platform.Iam.Domain.Model.ValueObjects.Permission", "Permissions", b1 =>
                        {
                            b1.Property<int>("RoleId")
                                .HasColumnType("int")
                                .HasColumnName("role_id");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("action");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("varchar(256)")
                                .HasColumnName("description");

                            b1.Property<string>("Resource")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("resource");

                            b1.HasKey("RoleId", "Id")
                                .HasName("p_k_role_permissions");

                            b1.ToTable("role_permissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoleId")
                                .HasConstraintName("f_k_role_permissions_roles_role_id");

                            b1.HasData(
                                new
                                {
                                    RoleId = 1,
                                    Id = 1,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-administrators",
                                    Resource = "administrators"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 2,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-users",
                                    Resource = "users"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 3,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 6,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.monitor-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 7,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.read-only",
                                    Resource = "operations"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 2,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-users",
                                    Resource = "users"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 3,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 6,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.monitor-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 7,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.read-only",
                                    Resource = "operations"
                                },
                                new
                                {
                                    RoleId = 3,
                                    Id = 3,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 3,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 3,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 4,
                                    Id = 6,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.monitor-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 4,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 5,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 5,
                                    Id = 7,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.read-only",
                                    Resource = "operations"
                                });
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ColdTrace.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_users_organizations_organization_id");

                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_users_roles_role_id");

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ColdTrace.Platform.MaintenanceManagement.Domain.Model.Aggregates.MaintenanceSchedule", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_maintenance_schedules_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_maintenance_schedules_organizations_organization_id");

                    b.Navigation("Asset");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.MaintenanceManagement.Domain.Model.Aggregates.TechnicalServiceRequest", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_technical_service_requests_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_technical_service_requests_organizations_organization_id");

                    b.Navigation("Asset");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.Reports.Domain.Model.Aggregates.Report", b =>
                {
                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_reports_organizations_organization_id");

                    b.Navigation("Organization");
                });
#pragma warning restore 612, 618
        }
    }
}
