// <auto-generated />
using System;
using ColdTrace.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColdTrace.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619143000_AddAlerts")]
    partial class AddAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("acknowledged_by");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("AssetName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("asset_name");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("detected_at");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset?>("LastNotificationAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_notification_at");

                    b.Property<string>("LastNotificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("last_notification_status");

                    b.Property<int>("NotificationCount")
                        .HasColumnType("int")
                        .HasColumnName("notification_count");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("ReadingId")
                        .HasColumnType("int")
                        .HasColumnName("reading_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("resolved_by");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("resolution_notes");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_incidents");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_incidents_asset_id");

                    b.HasIndex("OrganizationId", "AssetId")
                        .HasDatabaseName("i_x_incidents_organization_id_asset_id");

                    b.HasIndex("OrganizationId", "ReadingId")
                        .HasDatabaseName("i_x_incidents_organization_id_reading_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("i_x_incidents_organization_id_status");

                    b.ToTable("incidents");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("delivered_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("message");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Recipient")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("recipient");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("i_x_notifications_incident_id");

                    b.HasIndex("OrganizationId", "IncidentId")
                        .HasDatabaseName("i_x_notifications_organization_id_incident_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Incident", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_incidents_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_incidents_organizations_organization_id");

                    b.Navigation("Asset");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Notification", b =>
                {
                    b.HasOne("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications_incidents_incident_id");

                    b.HasOne("ColdTrace.Platform.Iam.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications_organizations_organization_id");

                    b.Navigation("Incident");

                    b.Navigation("Organization");
                });
#pragma warning restore 612, 618
        }
    }
}
