@coldtrace_platform_HostAddress = http://localhost:5269

GET {{coldtrace_platform_HostAddress}}/swagger/index.html
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/swagger/v1/swagger.json
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organizations
Content-Type: application/json
Accept: application/json

{
  "legalName": "ColdTrace Demo SAC",
  "commercialName": "ColdTrace Demo",
  "taxId": "20123456789",
  "contactEmail": "admin@coldtrace.demo"
}

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organization-sign-ups
Content-Type: application/json
Accept: application/json

{
  "legalName": "ColdTrace Sign Up SAC",
  "commercialName": "ColdTrace Sign Up",
  "taxId": "20987654321",
  "contactEmail": "owner@signup.demo",
  "firstName": "Mauricio",
  "lastName": "Pajes",
  "email": "mauricio@signup.demo"
}

###

GET {{coldtrace_platform_HostAddress}}/api/v1/roles
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/users
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/users
Content-Type: application/json
Accept: application/json

{
  "firstName": "Andrea",
  "lastName": "Torres",
  "email": "andrea@signup.demo",
  "roleId": 2
}

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/locations
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/locations/1
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/locations
Content-Type: application/json
Accept: application/json

{
  "name": "Main Cold Room",
  "type": "cold-room",
  "address": "Av. Industrial 123",
  "description": "Primary refrigerated storage area",
  "status": "active"
}

###

PUT {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/locations/1
Content-Type: application/json
Accept: application/json

{
  "name": "Main Cold Room",
  "type": "cold-room",
  "address": "Av. Industrial 123",
  "description": "Primary refrigerated storage area updated",
  "status": "active"
}

###
