@coldtrace_platform_HostAddress = http://localhost:5269
@accessToken = replace-with-token-from-sign-in

GET {{coldtrace_platform_HostAddress}}/swagger/index.html
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/swagger/v1/swagger.json
Accept: application/json

###

# Public landing-page catalog
GET {{coldtrace_platform_HostAddress}}/api/v1/subscription-plans
Accept: application/json

###

# Expected: 401 application/problem+json
GET {{coldtrace_platform_HostAddress}}/api/v1/organizations
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organization-sign-ups
Content-Type: application/json
Accept: application/json

{
  "legalName": "ColdTrace Sign Up SAC",
  "commercialName": "ColdTrace Sign Up",
  "taxId": "20987654321",
  "contactEmail": "owner@signup.demo",
  "firstName": "Mauricio",
  "lastName": "Pajes",
  "email": "mauricio@signup.demo",
  "password": "T58Smoke!2026"
}

###

POST {{coldtrace_platform_HostAddress}}/api/v1/authentication/sign-in
Content-Type: application/json
Accept: application/json

{
  "email": "mauricio@signup.demo",
  "password": "T58Smoke!2026"
}

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations
Authorization: Bearer {{accessToken}}
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organizations
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "legalName": "ColdTrace Demo SAC",
  "commercialName": "ColdTrace Demo",
  "taxId": "20123456789",
  "contactEmail": "admin@coldtrace.demo"
}

###

GET {{coldtrace_platform_HostAddress}}/api/v1/roles
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/users
Authorization: Bearer {{accessToken}}
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "firstName": "Andrea",
  "lastName": "Torres",
  "email": "andrea@signup.demo",
  "password": "UserSmoke!2026",
  "roleId": 2
}

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/locations
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/locations/1
Authorization: Bearer {{accessToken}}
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/locations
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "name": "Main Cold Room",
  "type": "cold-room",
  "address": "Av. Industrial 123",
  "description": "Primary refrigerated storage area",
  "status": "active"
}

###

PUT {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/locations/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "name": "Main Cold Room",
  "type": "cold-room",
  "address": "Av. Industrial 123",
  "description": "Primary refrigerated storage area updated",
  "status": "active"
}

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/gateways
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/gateways/1
Authorization: Bearer {{accessToken}}
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/gateways
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "locationId": 1,
  "uuid": "GW-001",
  "name": "Main Gateway",
  "network": "cold-room-wifi",
  "status": "active"
}

###

PUT {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/gateways/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "locationId": 1,
  "uuid": "GW-001",
  "name": "Main Gateway",
  "network": "cold-room-wifi-backup",
  "status": "active"
}

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/assets
Authorization: Bearer {{accessToken}}
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/assets
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "locationId": 1,
  "uuid": "ASSET-001",
  "type": "cold-room",
  "name": "Main Asset",
  "capacity": 12.5,
  "description": "Asset used to validate IoT device assignment",
  "status": "active"
}

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/iot-devices
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/iot-devices/1
Authorization: Bearer {{accessToken}}
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/iot-devices
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "gatewayId": 1,
  "assetId": 1,
  "uuid": "DEV-001",
  "name": "Main Sensor",
  "status": "active"
}

###

PUT {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/iot-devices/1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "gatewayId": 1,
  "assetId": 1,
  "uuid": "DEV-001",
  "name": "Main Sensor",
  "status": "active"
}

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/sensor-readings
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/sensor-readings/1
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/iot-devices/1/sensor-readings
Authorization: Bearer {{accessToken}}
Accept: application/json

###

POST {{coldtrace_platform_HostAddress}}/api/v1/organizations/1/iot-devices/1/sensor-readings
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "metric": "temperature",
  "value": 4.25,
  "unit": "C"
}

###
