// <auto-generated />
using System;
using ColdTrace.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColdTrace.Platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.AiResolutionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("approved_by");

                    b.Property<string>("CorrectiveActionDraft")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("corrective_action_draft");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("EscalationReason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("escalation_reason");

                    b.Property<bool>("EscalationRecommended")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("escalation_recommended");

                    b.Property<string>("EscalationUrgency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("escalation_urgency");

                    b.Property<string>("FinalCorrectiveAction")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("final_corrective_action");

                    b.Property<string>("FinalResolutionNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("final_resolution_notes");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelProvider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("model_provider");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProbableCause")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("probable_cause");

                    b.Property<string>("ProviderMetadata")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("provider_metadata");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("rejected_by");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("ResolutionNotesDraft")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("resolution_notes_draft");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_ai_resolution_plans");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("i_x_ai_resolution_plans_incident_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("i_x_ai_resolution_plans_organization_id_status");

                    b.HasIndex("OrganizationId", "IncidentId", "GeneratedAt")
                        .HasDatabaseName("i_x_ai_resolution_plans_organization_id_incident_id_generated_at");

                    b.ToTable("ai_resolution_plans");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("acknowledged_by");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("AssetName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("asset_name");

                    b.Property<string>("CorrectiveAction")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("corrective_action");

                    b.Property<DateTimeOffset?>("CorrectiveActionRegisteredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("corrective_action_registered_at");

                    b.Property<string>("CorrectiveActionRegisteredBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("corrective_action_registered_by");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("detected_at");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("escalated_at");

                    b.Property<string>("EscalatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("escalated_by");

                    b.Property<string>("EscalationReason")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("escalation_reason");

                    b.Property<DateTimeOffset?>("LastNotificationAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_notification_at");

                    b.Property<string>("LastNotificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("last_notification_status");

                    b.Property<int>("NotificationCount")
                        .HasColumnType("int")
                        .HasColumnName("notification_count");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("ReadingId")
                        .HasColumnType("int")
                        .HasColumnName("reading_id");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_incidents");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_incidents_asset_id");

                    b.HasIndex("OrganizationId", "AssetId")
                        .HasDatabaseName("i_x_incidents_organization_id_asset_id");

                    b.HasIndex("OrganizationId", "ReadingId")
                        .HasDatabaseName("i_x_incidents_organization_id_reading_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("i_x_incidents_organization_id_status");

                    b.ToTable("incidents");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("delivered_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("message");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Recipient")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("recipient");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("i_x_notifications_incident_id");

                    b.HasIndex("OrganizationId", "IncidentId")
                        .HasDatabaseName("i_x_notifications_organization_id_incident_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("Capacity")
                        .HasColumnType("double")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_assets");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("i_x_assets_location_id");

                    b.HasIndex("OrganizationId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_assets_organization_id_uuid");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.AssetSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AlertThresholdMinutes")
                        .HasColumnType("int")
                        .HasColumnName("alert_threshold_minutes");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<int>("CalibrationFrequencyDays")
                        .HasColumnType("int")
                        .HasColumnName("calibration_frequency_days");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("HumidityUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("humidity_unit");

                    b.Property<double>("MaximumHumidity")
                        .HasColumnType("double")
                        .HasColumnName("maximum_humidity");

                    b.Property<double>("MaximumTemperature")
                        .HasColumnType("double")
                        .HasColumnName("maximum_temperature");

                    b.Property<double>("MinimumHumidity")
                        .HasColumnType("double")
                        .HasColumnName("minimum_humidity");

                    b.Property<double>("MinimumTemperature")
                        .HasColumnType("double")
                        .HasColumnName("minimum_temperature");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("ReadingFrequencySeconds")
                        .HasColumnType("int")
                        .HasColumnName("reading_frequency_seconds");

                    b.Property<string>("TemperatureUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("temperature_unit");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("weight_unit");

                    b.HasKey("Id")
                        .HasName("p_k_asset_settings");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_asset_settings_asset_id");

                    b.HasIndex("OrganizationId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("i_x_asset_settings_organization_id_asset_id");

                    b.ToTable("asset_settings");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Gateway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("network");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_gateways");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("i_x_gateways_location_id");

                    b.HasIndex("OrganizationId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_gateways_organization_id_uuid");

                    b.ToTable("gateways");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.IotDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("CalibrationStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("calibration_status");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("device_type");

                    b.Property<int>("GatewayId")
                        .HasColumnType("int")
                        .HasColumnName("gateway_id");

                    b.Property<DateTime>("LastCalibrationDate")
                        .HasColumnType("date")
                        .HasColumnName("last_calibration_date");

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("measurement_type");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("NextCalibrationDate")
                        .HasColumnType("date")
                        .HasColumnName("next_calibration_date");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("ReadingFrequencySeconds")
                        .HasColumnType("int")
                        .HasColumnName("reading_frequency_seconds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_iot_devices");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_iot_devices_asset_id");

                    b.HasIndex("GatewayId")
                        .HasDatabaseName("i_x_iot_devices_gateway_id");

                    b.HasIndex("OrganizationId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_iot_devices_organization_id_uuid");

                    b.ToTable("iot_devices");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_locations");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_locations_organization_id_name");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("ColdTrace.Platform.Billing.Domain.Model.Aggregates.OrganizationSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset?>("CurrentPeriodStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("current_period_start");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("metadata");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("plan_code");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("provider_customer_id");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("provider_subscription_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organization_subscriptions");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("i_x_organization_subscriptions_organization_id");

                    b.HasIndex("ProviderCustomerId")
                        .HasDatabaseName("i_x_organization_subscriptions_provider_customer_id");

                    b.HasIndex("ProviderSubscriptionId")
                        .HasDatabaseName("i_x_organization_subscriptions_provider_subscription_id");

                    b.ToTable("organization_subscriptions");
                });

            modelBuilder.Entity("ColdTrace.Platform.Billing.Domain.Model.Entities.BillingWebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("event_type");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("metadata");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("provider_customer_id");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("provider_subscription_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_billing_webhook_events");

                    b.HasIndex("Provider", "EventId")
                        .IsUnique()
                        .HasDatabaseName("uk_billing_webhook_events_provider_event");

                    b.ToTable("billing_webhook_events");
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("commercial_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tax_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organizations");

                    b.HasIndex("ContactEmail")
                        .IsUnique()
                        .HasDatabaseName("i_x_organizations_contact_email");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("i_x_organizations_tax_id");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.PasswordResetRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("consumed_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requested_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_password_reset_requests");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("i_x_password_reset_requests_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_password_reset_requests_user_id");

                    b.ToTable("password_reset_requests");
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_roles_name");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Super Administrator",
                            Name = "super-admin"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Administrator",
                            Name = "administrator"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Operations Manager",
                            Name = "operations-manager"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Operator",
                            Name = "operator"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Auditor",
                            Name = "auditor"
                        });
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("last_name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("OrganizationUserId")
                        .HasColumnType("int")
                        .HasColumnName("organization_user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Uuid")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_users_organization_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_users_role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ColdTrace.Platform.MaintenanceManagement.Domain.Model.Aggregates.MaintenanceSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("FrequencyDays")
                        .HasColumnType("int")
                        .HasColumnName("frequency_days");

                    b.Property<string>("Observations")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("observations");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("ResponsibleUserId")
                        .HasColumnType("int")
                        .HasColumnName("responsible_user_id");

                    b.Property<DateTimeOffset>("ScheduledDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_maintenance_schedules");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_maintenance_schedules_asset_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_maintenance_schedules_organization_id");

                    b.ToTable("maintenance_schedules");
                });

            modelBuilder.Entity("ColdTrace.Platform.MaintenanceManagement.Domain.Model.Aggregates.TechnicalServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<int>("AssetLocationId")
                        .HasColumnType("int")
                        .HasColumnName("asset_location_id");

                    b.Property<string>("AssetName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("asset_name");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("closed_by");

                    b.Property<string>("ClosureSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("closure_summary");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("evidence");

                    b.Property<int?>("IncidentId")
                        .HasColumnType("int")
                        .HasColumnName("incident_id");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("issue_description");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_technical_service_requests");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_technical_service_requests_asset_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_technical_service_requests_organization_id");

                    b.ToTable("technical_service_requests");
                });

            modelBuilder.Entity("ColdTrace.Platform.Monitoring.Domain.Model.Aggregates.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("int")
                        .HasColumnName("battery_level");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("GatewayId")
                        .HasColumnType("int")
                        .HasColumnName("gateway_id");

                    b.Property<double?>("Humidity")
                        .HasPrecision(8, 2)
                        .HasColumnType("double")
                        .HasColumnName("humidity");

                    b.Property<bool?>("ImageCaptured")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("image_captured");

                    b.Property<int>("IotDeviceId")
                        .HasColumnType("int")
                        .HasColumnName("iot_device_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<bool?>("MotionDetected")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("motion_detected");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<bool>("OutOfRange")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("out_of_range");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<int?>("SignalStrength")
                        .HasColumnType("int")
                        .HasColumnName("signal_strength");

                    b.Property<double?>("Temperature")
                        .HasPrecision(8, 2)
                        .HasColumnType("double")
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_sensor_readings");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_sensor_readings_asset_id");

                    b.HasIndex("GatewayId")
                        .HasDatabaseName("i_x_sensor_readings_gateway_id");

                    b.HasIndex("IotDeviceId")
                        .HasDatabaseName("i_x_sensor_readings_iot_device_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_sensor_readings_organization_id");

                    b.HasIndex("OrganizationId", "RecordedAt")
                        .HasDatabaseName("i_x_sensor_readings_organization_id_recorded_at");

                    b.HasIndex("OrganizationId", "AssetId", "RecordedAt")
                        .HasDatabaseName("i_x_sensor_readings_organization_id_asset_id_recorded_at");

                    b.ToTable("sensor_readings");
                });

            modelBuilder.Entity("ColdTrace.Platform.Reports.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AssetCount")
                        .HasColumnType("int")
                        .HasColumnName("asset_count");

                    b.Property<double?>("AverageHumidity")
                        .HasColumnType("double")
                        .HasColumnName("average_humidity");

                    b.Property<double?>("AverageTemperature")
                        .HasColumnType("double")
                        .HasColumnName("average_temperature");

                    b.Property<double?>("CompliancePercentage")
                        .HasColumnType("double")
                        .HasColumnName("compliance_percentage");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("int")
                        .HasColumnName("incident_count");

                    b.Property<int>("OpenIncidentCount")
                        .HasColumnType("int")
                        .HasColumnName("open_incident_count");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("OutOfRangeReadingCount")
                        .HasColumnType("int")
                        .HasColumnName("out_of_range_reading_count");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("period_start");

                    b.Property<int>("ReadingCount")
                        .HasColumnType("int")
                        .HasColumnName("reading_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_reports");

                    b.HasIndex("OrganizationId", "GeneratedAt")
                        .HasDatabaseName("i_x_reports_organization_id_generated_at");

                    b.HasIndex("OrganizationId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_reports_organization_id_uuid");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.AiResolutionPlan", b =>
                {
                    b.HasOne("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_ai_resolution_plans_incidents_incident_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_ai_resolution_plans_organizations_organization_id");

                    b.OwnsMany("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.AiResolutionPlanRequiredEvidence", "RequiredEvidenceItems", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("AiResolutionPlanId")
                                .HasColumnType("int")
                                .HasColumnName("ai_resolution_plan_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("p_k_ai_resolution_plan_required_evidences");

                            b1.HasIndex("AiResolutionPlanId")
                                .HasDatabaseName("i_x_ai_resolution_plan_required_evidences_ai_resolution_plan_id");

                            b1.ToTable("ai_resolution_plan_required_evidences", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AiResolutionPlanId")
                                .HasConstraintName("f_k_ai_resolution_plan_required_evidence_ai_resolution_plan_id");
                        });

                    b.OwnsMany("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.AiResolutionPlanStep", "RecommendedSteps", b1 =>
                        {
                            b1.Property<int>("AiResolutionPlanId")
                                .HasColumnType("int")
                                .HasColumnName("ai_resolution_plan_id");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int")
                                .HasColumnName("sequence");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)")
                                .HasColumnName("action");

                            b1.Property<string>("ExpectedOutcome")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)")
                                .HasColumnName("expected_outcome");

                            b1.Property<string>("Rationale")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)")
                                .HasColumnName("rationale");

                            b1.HasKey("AiResolutionPlanId", "Sequence")
                                .HasName("p_k_ai_resolution_plan_steps");

                            b1.ToTable("ai_resolution_plan_steps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AiResolutionPlanId")
                                .HasConstraintName("f_k_ai_resolution_plan_steps_ai_resolution_plan_id");
                        });

                    b.OwnsMany("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.AiResolutionPlanUncertaintyNote", "UncertaintyNoteItems", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("AiResolutionPlanId")
                                .HasColumnType("int")
                                .HasColumnName("ai_resolution_plan_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("p_k_ai_resolution_plan_uncertainty_notes");

                            b1.HasIndex("AiResolutionPlanId")
                                .HasDatabaseName("i_x_ai_resolution_plan_uncertainty_notes_ai_resolution_plan_id");

                            b1.ToTable("ai_resolution_plan_uncertainty_notes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AiResolutionPlanId")
                                .HasConstraintName("f_k_ai_resolution_plan_uncertainty_notes_ai_resolution_plan_id");
                        });

                    b.Navigation("Incident");

                    b.Navigation("Organization");

                    b.Navigation("RecommendedSteps");

                    b.Navigation("RequiredEvidenceItems");

                    b.Navigation("UncertaintyNoteItems");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Incident", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_incidents_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_incidents_organizations_organization_id");

                    b.Navigation("Asset");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Notification", b =>
                {
                    b.HasOne("ColdTrace.Platform.Alerts.Domain.Model.Aggregates.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications_incidents_incident_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_notifications_organizations_organization_id");

                    b.Navigation("Incident");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_assets_locations_location_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assets_organizations_organization_id");

                    b.Navigation("Location");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.AssetSettings", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_asset_settings_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_asset_settings_organizations_organization_id");

                    b.OwnsMany("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.AssetSettingsAssetType", "AssetTypeEntries", b1 =>
                        {
                            b1.Property<int>("AssetSettingsId")
                                .HasColumnType("int")
                                .HasColumnName("asset_settings_id");

                            b1.Property<string>("AssetType")
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("asset_type");

                            b1.HasKey("AssetSettingsId", "AssetType")
                                .HasName("p_k_asset_settings_asset_types");

                            b1.ToTable("asset_settings_asset_types", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssetSettingsId")
                                .HasConstraintName("f_k_asset_settings_asset_types_asset_settings_id");
                        });

                    b.OwnsMany("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.AssetSettingsIotDeviceType", "IotDeviceTypeEntries", b1 =>
                        {
                            b1.Property<int>("AssetSettingsId")
                                .HasColumnType("int")
                                .HasColumnName("asset_settings_id");

                            b1.Property<string>("IotDeviceType")
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("iot_device_type");

                            b1.HasKey("AssetSettingsId", "IotDeviceType")
                                .HasName("p_k_asset_settings_iot_device_types");

                            b1.ToTable("asset_settings_iot_device_types", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssetSettingsId")
                                .HasConstraintName("f_k_asset_settings_iot_device_types_asset_settings_id");
                        });

                    b.Navigation("Asset");

                    b.Navigation("AssetTypeEntries");

                    b.Navigation("IotDeviceTypeEntries");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Gateway", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_gateways_locations_location_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_gateways_organizations_organization_id");

                    b.Navigation("Location");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.IotDevice", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_iot_devices_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Gateway", "Gateway")
                        .WithMany()
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_iot_devices_gateways_gateway_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_iot_devices_organizations_organization_id");

                    b.OwnsMany("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.IotDeviceMeasurementParameter", "MeasurementParameterEntries", b1 =>
                        {
                            b1.Property<int>("IotDeviceId")
                                .HasColumnType("int")
                                .HasColumnName("iot_device_id");

                            b1.Property<string>("MeasurementParameter")
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("measurement_parameter");

                            b1.HasKey("IotDeviceId", "MeasurementParameter")
                                .HasName("p_k_iot_device_measurement_parameters");

                            b1.ToTable("iot_device_measurement_parameters", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("IotDeviceId")
                                .HasConstraintName("f_k_iot_device_measurement_parameters_iot_device_id");
                        });

                    b.Navigation("Asset");

                    b.Navigation("Gateway");

                    b.Navigation("MeasurementParameterEntries");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", b =>
                {
                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_locations_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.Billing.Domain.Model.Aggregates.OrganizationSubscription", b =>
                {
                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_organization_subscriptions_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.PasswordResetRequest", b =>
                {
                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_password_reset_requests_users_user_id");
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Role", b =>
                {
                    b.OwnsMany("ColdTrace.Platform.IdentityAccess.Domain.Model.ValueObjects.Permission", "Permissions", b1 =>
                        {
                            b1.Property<int>("RoleId")
                                .HasColumnType("int")
                                .HasColumnName("role_id");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("action");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("varchar(256)")
                                .HasColumnName("description");

                            b1.Property<string>("Resource")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("resource");

                            b1.HasKey("RoleId", "Id")
                                .HasName("p_k_role_permissions");

                            b1.ToTable("role_permissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoleId")
                                .HasConstraintName("f_k_role_permissions_roles_role_id");

                            b1.HasData(
                                new
                                {
                                    RoleId = 1,
                                    Id = 1,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-administrators",
                                    Resource = "administrators"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 2,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-users",
                                    Resource = "users"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 3,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 6,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.monitor-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 7,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.read-only",
                                    Resource = "operations"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 2,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-users",
                                    Resource = "users"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 3,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 6,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.monitor-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 7,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.read-only",
                                    Resource = "operations"
                                },
                                new
                                {
                                    RoleId = 3,
                                    Id = 3,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 3,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 3,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 4,
                                    Id = 6,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.monitor-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 4,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 5,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 5,
                                    Id = 7,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.read-only",
                                    Resource = "operations"
                                });
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.User", b =>
                {
                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_users_organizations_organization_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_users_roles_role_id");

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ColdTrace.Platform.MaintenanceManagement.Domain.Model.Aggregates.MaintenanceSchedule", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_maintenance_schedules_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_maintenance_schedules_organizations_organization_id");

                    b.Navigation("Asset");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.MaintenanceManagement.Domain.Model.Aggregates.TechnicalServiceRequest", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_technical_service_requests_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_technical_service_requests_organizations_organization_id");

                    b.Navigation("Asset");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.Monitoring.Domain.Model.Aggregates.SensorReading", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_sensor_readings_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Gateway", "Gateway")
                        .WithMany()
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_sensor_readings_gateways_gateway_id");

                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.IotDevice", "IotDevice")
                        .WithMany()
                        .HasForeignKey("IotDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sensor_readings_iot_devices_iot_device_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sensor_readings_organizations_organization_id");

                    b.Navigation("Asset");

                    b.Navigation("Gateway");

                    b.Navigation("IotDevice");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.Reports.Domain.Model.Aggregates.Report", b =>
                {
                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_reports_organizations_organization_id");

                    b.Navigation("Organization");
                });
#pragma warning restore 612, 618
        }
    }
}
