// <auto-generated />
using System;
using ColdTrace.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColdTrace.Platform.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("Capacity")
                        .HasColumnType("double")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_assets");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("i_x_assets_location_id");

                    b.HasIndex("OrganizationId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_assets_organization_id_uuid");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Gateway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("network");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_gateways");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("i_x_gateways_location_id");

                    b.HasIndex("OrganizationId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_gateways_organization_id_uuid");

                    b.ToTable("gateways");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.IotDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("GatewayId")
                        .HasColumnType("int")
                        .HasColumnName("gateway_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_iot_devices");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("i_x_iot_devices_asset_id");

                    b.HasIndex("GatewayId")
                        .HasDatabaseName("i_x_iot_devices_gateway_id");

                    b.HasIndex("OrganizationId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("i_x_iot_devices_organization_id_uuid");

                    b.ToTable("iot_devices");
                });

            modelBuilder.Entity("ColdTrace.Platform.Monitoring.Domain.Model.Aggregates.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("recorded_at");

                    b.Property<int>("IotDeviceId")
                        .HasColumnType("int")
                        .HasColumnName("iot_device_id");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("metric");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("unit");

                    b.Property<decimal>("Value")
                        .IsRequired()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("value");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_sensor_readings");

                    b.HasIndex("IotDeviceId")
                        .HasDatabaseName("i_x_sensor_readings_iot_device_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_sensor_readings_organization_id");

                    b.HasIndex("OrganizationId", "RecordedAt")
                        .HasDatabaseName("i_x_sensor_readings_organization_id_recorded_at");

                    b.ToTable("sensor_readings");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_locations");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_locations_organization_id_name");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("commercial_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tax_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organizations");

                    b.HasIndex("ContactEmail")
                        .IsUnique()
                        .HasDatabaseName("i_x_organizations_contact_email");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("i_x_organizations_tax_id");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_roles_name");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Super Administrator",
                            Name = "super-admin"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Administrator",
                            Name = "administrator"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Operations Manager",
                            Name = "operations-manager"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Operator",
                            Name = "operator"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Auditor",
                            Name = "auditor"
                        });
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("last_name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int?>("OrganizationUserId")
                        .HasColumnType("int")
                        .HasColumnName("organization_user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Uuid")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_users_organization_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_users_role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_assets_locations_location_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_assets_organizations_organization_id");

                    b.Navigation("Location");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Gateway", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_gateways_locations_location_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_gateways_organizations_organization_id");

                    b.Navigation("Location");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.IotDevice", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_iot_devices_assets_asset_id");

                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Gateway", "Gateway")
                        .WithMany()
                        .HasForeignKey("GatewayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_iot_devices_gateways_gateway_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_iot_devices_organizations_organization_id");

                    b.Navigation("Asset");

                    b.Navigation("Gateway");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.Monitoring.Domain.Model.Aggregates.SensorReading", b =>
                {
                    b.HasOne("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.IotDevice", "IotDevice")
                        .WithMany()
                        .HasForeignKey("IotDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sensor_readings_iot_devices_iot_device_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sensor_readings_organizations_organization_id");

                    b.Navigation("IotDevice");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.AssetManagement.Domain.Model.Aggregates.Location", b =>
                {
                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_locations_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Role", b =>
                {
                    b.OwnsMany("ColdTrace.Platform.IdentityAccess.Domain.Model.ValueObjects.Permission", "Permissions", b1 =>
                        {
                            b1.Property<int>("RoleId")
                                .HasColumnType("int")
                                .HasColumnName("role_id");

                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("action");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("varchar(256)")
                                .HasColumnName("description");

                            b1.Property<string>("Resource")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("resource");

                            b1.HasKey("RoleId", "Id")
                                .HasName("p_k_role_permissions");

                            b1.ToTable("role_permissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoleId")
                                .HasConstraintName("f_k_role_permissions_roles_role_id");

                            b1.HasData(
                                new
                                {
                                    RoleId = 1,
                                    Id = 1,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-administrators",
                                    Resource = "administrators"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 2,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-users",
                                    Resource = "users"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 3,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 6,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.monitor-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 1,
                                    Id = 7,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.read-only",
                                    Resource = "operations"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 2,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-users",
                                    Resource = "users"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 3,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 6,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.monitor-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 2,
                                    Id = 7,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.read-only",
                                    Resource = "operations"
                                },
                                new
                                {
                                    RoleId = 3,
                                    Id = 3,
                                    Action = "manage",
                                    Description = "roles-permissions.permissions.manage-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 3,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 3,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 4,
                                    Id = 6,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.monitor-assets",
                                    Resource = "assets"
                                },
                                new
                                {
                                    RoleId = 4,
                                    Id = 5,
                                    Action = "update",
                                    Description = "roles-permissions.permissions.resolve-alerts",
                                    Resource = "alerts"
                                },
                                new
                                {
                                    RoleId = 5,
                                    Id = 4,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.view-reports",
                                    Resource = "reports"
                                },
                                new
                                {
                                    RoleId = 5,
                                    Id = 7,
                                    Action = "view",
                                    Description = "roles-permissions.permissions.read-only",
                                    Resource = "operations"
                                });
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.User", b =>
                {
                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_users_organizations_organization_id");

                    b.HasOne("ColdTrace.Platform.IdentityAccess.Domain.Model.Aggregates.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_users_roles_role_id");

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
